name: Feature request
description: Suggest an idea for this project for one of FaserF's Custom Addon's
title: "[Feature Request]: "
labels: ["enhancement"]
assignees:
  - FaserF
body:
  - type: markdown
    attributes:
      value: |
        This feature request request form is for feature requests only!

        If you have a bug or issue request, please use the bug report template!
  - type: textarea
    validations:
      required: true
    attributes:
      label: The request
      description: >-
        A clear and concise description of what you want to happen.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: dropdown
    validations:
      required: true
    attributes:
      label: For which Add-On
      description: >
        The name of the Addon you are wishing a new feature. For example: Apache2
      options:
        - Apache2
        - Apache2-Minimal-MariaDB
        - Apache2-Minimal
        - Assistant Relay
        - Bash_Script_Executer
        - BT-MQTT-Gateway
        - Freenom-DNS-Updater
        - Netboot-XYZ
        - OpenSSL
        - Switch_LAN_Play
        - Switch_LAN_Play_Server
        - Tuya-Convert
        - Wiki.JS
        - xqrepack
        - Other
  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      render: txt
      description: >-
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
